# Generated by Django 4.0.8 on 2025-08-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_populate_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['code'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пример', 'verbose_name_plural': 'Примеры'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ['-added_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['code'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['code'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['from_word', 'order'], 'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word'], 'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
        migrations.AlterModelOptions(
            name='wordlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Оценка слова', 'verbose_name_plural': 'Оценки слов'},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='example',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_examples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='example',
            name='text',
            field=models.TextField(help_text='Пример использования слова'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly идентификатор', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='note',
            field=models.CharField(blank=True, help_text='Дополнительные примечания к переводу', max_length=100),
        ),
        migrations.AlterField(
            model_name='translation',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения переводов'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], default='approved', help_text='Статус перевода', max_length=10),
        ),
        migrations.AlterField(
            model_name='wordlike',
            name='is_like',
            field=models.BooleanField(help_text='True для лайка, False для дизлайка'),
        ),
        migrations.AlterField(
            model_name='wordlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['created_at'], name='dictionary__created_78f1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['difficulty'], name='dictionary__difficu_8d1631_idx'),
        ),
    ]
