# Generated by Django 4.0.8 on 2025-08-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_word_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('none', 'Без уровня'), ('hidden', 'Не показывать'), ('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='none', max_length=10, null=True),
        ),
    ]
