# Generated by Django 4.0.8 on 2025-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_word_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_mode',
            field=models.CharField(choices=[('visible', 'Показывать'), ('hidden', 'Скрыть')], default='visible', help_text='Режим отображения тега', max_length=10),
        ),
    ]
